services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc 127.0.0.1 2181 | grep imok"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - chokak-network

  kafka-1:
    image: wurstmeister/kafka:latest
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG_DIRS: /kafka-logs
      KAFKA_HOST_NAME: kafka-1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
    depends_on:
      - zookeeper-1
    volumes:
      - kafka-data:/kafka-logs
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - chokak-network

  postgres-1:
    image: postgres:15
    container_name: postgres-1
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - chokak-network

  chokak-cloud-storage:
    build:
      context: ./services/chokak-cloud-storage
      dockerfile: Dockerfile
    image: chokak-cloud-storage:latest
    container_name: chokak-cloud-storage
    ports:
      - "8088:8088"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8088"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - chokak-network

  chokak-gateway-server:
    build:
      context: ./services/chokak-gateway-server
      dockerfile: Dockerfile
    image: chokak-gateway-server:latest
    container_name: chokak-gateway-server
    ports:
      - "8000:8000"
    depends_on:
      - chokak-cloud-storage
      - chokak-server
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - chokak-network

  chokak-server:
    build:
      context: ./services/chokak-server
      dockerfile: Dockerfile
    image: chokak-server:latest
    container_name: chokak-server
    ports:
      - "8084:8084"
    depends_on:
      - postgres-1
      - chokak-cloud-storage
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8084"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - chokak-network

networks:
  chokak-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  zookeeper-data:
    driver: local
  zookeeper-logs:
    driver: local
  kafka-data:
    driver: local